
version: "3.4"

networks:
  ocach-network:
    driver: bridge

services:
  api:
    container_name: ocach-api
    image: ocach/api
    restart: always
    depends_on:
      - redis
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings:Redis: redis:6379,ssl=False,abortConnect=False
    ports:
      - 5000:5000
    networks:
      - ocach-network
    volumes:
      - ~/.aspnet/https:/https:ro

  redis:
    container_name: ocach-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - ocach-network